      - name: Check disk space (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Get-PSDrive C | Select-Object Used,Free

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-make  # Added make
        timeout-minutes: 20
        continue-on-error: true

      - name: Debug MSYS2 failure (Windows)
        if: runner.os == 'Windows' && steps['Install dependencies (Windows)'].outcome == 'failure'
        shell: powershell
        run: |
          dir C:\hostedtoolcache\windows\msys2-installer\0.0.20250221\x64
          if (Test-Path C:\hostedtoolcache\windows\msys2-installer\0.0.20250221\x64\base.exe) {
            Write-Output "base.exe exists, size: $((Get-Item C:\hostedtoolcache\windows\msys2-installer\0.0.20250221\x64\base.exe).Length) bytes"
          } else {
            Write-Output "base.exe not found!"
          }

      - name: Create build directory (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          mkdir -p build && echo "Build directory ready."

      - name: Verify MinGW tools (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          which gcc
          which g++
          which mingw32-make
          echo "PATH is: $PATH"

      - name: Configure CMake project (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM=mingw32-make -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

      - name: Build C++ code (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd build
          cmake --build .

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd build
          if [ -f "./main.exe" ]; then
            ./main.exe
          else
            echo "Error: main.exe not found! Build may have failed."
            exit 1
          fi